Feature/143 market add item repository
AlexBimlnk/ComputerMarket pull request #145
Opened 2022-11-29 20:40 UTC by wi1sp

2022-11-29 21:27 UTC, AlexBimlnk requested changes
в тест хелпере я считаю не надо было делать методы под те объекты которые создаются пару раз за все тесты. Видел там коллекция с него же генерилась, а это неудобно, нужно смотреть тест кейсы. Вообще лучше посмотреть ссылки у методов и если их мало, то вернуть логику на место и убрать эти методы из хелпера

2022-11-29 21:27 UTC, AlexBimlnk commented on Databases/Market/Migrations/9_change_item_property.sql
> +DELETE FROM db_version WHERE TRUE;
update обычный не нас, правильно

2022-11-29 21:27 UTC, AlexBimlnk commented on Market.Logic.Tests/Storage/UsersRepository.Tests.cs
> +        var inccorectUserPassword = "none" + user.AuthenticationData.Password.Value;
не надо, совершенно непонятно по тесту какой пароль инкоректный, неудобно получается

2022-11-29 21:27 UTC, AlexBimlnk commented on Market.Logic.Tests/TestHelper.cs
> +using TItemType = Market.Logic.Storage.Models.ItemType;
зачем все эти юзинги? Тут разве конфлиты имен какие то? вроде названия везде разные

2022-11-29 21:27 UTC, AlexBimlnk commented on Market.Logic/Models/ItemProperty.cs
> +    public void SetValue(string value)
вообще наверное можно эту логику сразу в свойство перенести, чем метод делать

2022-11-29 21:27 UTC, AlexBimlnk commented on Market.Logic/Models/ItemProperty.cs
> +    public PropertyGroup Group { get; }
описание. здесь и ниже

2022-11-29 21:27 UTC, AlexBimlnk commented on Market.Logic/Models/ItemType.cs
> +        if (id <= 0)
так может воспользоваться обычным ID? Куда уже инакпсулировать уже какую то логику валидности

2022-11-29 21:27 UTC, AlexBimlnk commented on Market.Logic/Models/PropertyDataType.cs
> +public enum PropertyDataType
описание

2022-11-29 21:27 UTC, AlexBimlnk commented on Market.Logic/Models/PropertyGroup.cs
> +public sealed class PropertyGroup
не описан класс

2022-11-29 21:27 UTC, AlexBimlnk commented on Market.Logic/Models/PropertyGroup.cs
> +        if (id <= 0)
аналогично

2022-11-29 21:27 UTC, AlexBimlnk commented on Market.Logic/Storage/Models/ItemProperty.cs
> +    public PropertyDataTypeId PropertyDataTypeId { get; set; }
описание

2022-11-29 21:27 UTC, AlexBimlnk commented on Market.Logic/Storage/Models/PropertyDataType.cs
> +public class PropertyDataType
описание

2022-11-29 21:27 UTC, AlexBimlnk commented on Market.Logic/Storage/Models/PropertyDataTypeId.cs
> +public enum PropertyDataTypeId : int
Не понял зачем две енамки одинаковые? Не нужны две. Одной достаточно, не надо отедельно под каждую модель заводить

2022-11-29 21:27 UTC, AlexBimlnk commented on Market.Logic/Storage/Repositories/IItemsRepository.cs
> +public interface IItemsRepository : IKeyableRepository<Item, ID>
Описание

2022-11-29 21:27 UTC, AlexBimlnk commented on Market.Logic/Storage/Repositories/ItemsRepository.cs
> +
лишняя строка

2022-11-29 21:27 UTC, AlexBimlnk commented on Market.Logic/Storage/Repositories/ItemsRepository.cs
> +    public ItemsRepository(IRepositoryContext context, ILogger<ItemsRepository> logger)
описание

2022-11-29 21:27 UTC, AlexBimlnk commented on Market.Logic/Storage/Repositories/RepositoryHelper.cs
> +public abstract class RepositoryHelper
Ой не надо так. Оставь отдельные методы у каждого репозитория.
К тому же наследование семантически неверное. Нельзя сказать что репозиторий является хелпером репозитория.
Короче это дичь. Два метода погоды в репозиториях не сделают. Не надо. Оставь инкапусляцию. Если так хочется, то лучше в самих сторожевых моделях метод конвертации описать. Хотя я в этом особого смысла не вижу.

2022-11-29 21:27 UTC, AlexBimlnk commented on Market.Logic/Storage/Repositories/ProductsRepository.cs
> +public sealed class ProductsRepository : RepositoryHelper, IKeyableRepository<Product, (long, long)>
сематический бред

2022-11-29 21:27 UTC, AlexBimlnk commented on Market.Logic/Storage/Repositories/ProductsRepository.cs
> +public sealed class ProductsRepository : RepositoryHelper, IKeyableRepository<Product, (long, long)>
И почему у нас ключ (long, long). А не (ID, ID)?

2022-11-29 21:27 UTC, AlexBimlnk commented on Market.Logic/Storage/Repositories/UsersRepository.cs
> +            .Select(x => ConvertFromStorageModel(x, _logger))
жесть

2022-12-02 23:25 UTC, AlexBimlnk requested changes

2022-12-02 23:25 UTC, AlexBimlnk commented on Market.Logic.Tests/Storage/ProductsRepository.IntergrationTests.cs
> +        .Select(x => { x.Description = null!; x.Type = null!; return x; })
и че это? почему зачем

2022-12-02 23:25 UTC, AlexBimlnk commented on Market.Logic.Tests/Storage/ProductsRepository.IntergrationTests.cs
> +            .Select(x => { x.ItemId = inputItem.Key.Value; x.Property= null!; return x; })
то же самое. Может тогда не пользоваться хелперами а нормально объекты какие надо создать?

2022-12-02 23:25 UTC, AlexBimlnk commented on Market.Logic.Tests/Storage/ProductsRepository.IntergrationTests.cs
> +            .Select(x => { AddItemPropertyAsync(x).Wait(); return Task.CompletedTask; })
А это что? await? Или просто AddItemPropertyAsync(x)

2022-12-02 23:25 UTC, AlexBimlnk commented on Market.Logic.Tests/Storage/ProductsRepository.IntergrationTests.cs
> +            .Select(x => { AddItemPropertyAsync(x).Wait(); return Task.CompletedTask; })
аналогично

2022-12-02 23:25 UTC, AlexBimlnk commented on Market.Logic.Tests/Storage/ProductsRepository.IntergrationTests.cs
> +        await Task.WhenAll(properties.Select(x => { AddItemPropertyAsync(x).Wait(); return Task.CompletedTask; }).ToArray());
и здесь

2022-12-02 23:25 UTC, AlexBimlnk commented on Market.Logic.Tests/Storage/ProductsRepository.IntergrationTests.cs
> +        /*
убрать если не нужно

2022-12-02 23:25 UTC, AlexBimlnk commented on Market.Logic.Tests/Storage/ProductsRepository.IntergrationTests.cs
> +                    1,
тут табы лишние

2022-12-02 23:25 UTC, AlexBimlnk commented on Market.Logic/Storage/Repositories/IProductsRepository.cs
> +    public Task AddOrUpdateProductAsync(Product product, CancellationToken token = default);
слово Product уберите пожалуйста

2022-12-02 23:25 UTC, AlexBimlnk commented on Market.Logic/Storage/Repositories/IProductsRepository.cs
> +    public Task AddProductRangeAsync(IReadOnlyCollection<Product> products);
И здесь

2022-12-02 23:25 UTC, AlexBimlnk commented on Market.Logic/Storage/Repositories/IProductsRepository.cs
> +    public void RemoveProduct(Product product);
И здесь и так далее

2022-12-02 23:25 UTC, AlexBimlnk commented on Market.Logic/Storage/Repositories/IProductsRepository.cs
> +    public void RemoveProduct((ID, ID) key);
Зачем этот метод?

2022-12-02 23:25 UTC, AlexBimlnk commented on Market.Logic/Storage/Repositories/IProductsRepository.cs
> +    public void Update(Item item);
зачем этот метод?*

2022-12-02 23:25 UTC, AlexBimlnk commented on Market.Logic/Storage/Repositories/IProductsRepository.cs
> +    public Task<bool> ContainsProductAsync((ID, ID) key, CancellationToken token = default);
Почему контейнс по id? А не по сущности. Ведь для этого и вводиться IKeyable. Чтобы не разбираться с ключами потребителям.

2022-12-02 23:25 UTC, AlexBimlnk commented on Market.Logic/Storage/Repositories/IProductsRepository.cs
> +public interface IProductsRepository : IKeyableRepository<Item, ID>
IKeyableRepository<Product, ID> вообще то

2022-12-02 23:25 UTC, AlexBimlnk commented on Market.Logic/Storage/Repositories/IProductsRepository.cs
> +    public Product? GetProduct((ID, ID) key);
это вроде долежн быть getByKey

2022-12-02 23:25 UTC, AlexBimlnk commented on Market.Logic/Storage/Repositories/IProductsRepository.cs
> +    public IEnumerable<Product> GetAllProducts();
зачем этот метод. Интерфейс просто имплементируем IKeyableRepo<Product>

2022-12-02 23:25 UTC, AlexBimlnk commented on Market.Logic/Storage/Repositories/IProductsRepository.cs
> +    public IEnumerable<Product> GetAllItemProducts(Item item);
а это зачем?

2022-12-02 23:25 UTC, AlexBimlnk commented on Market.Logic/Storage/Repositories/IProductsRepository.cs
> +namespace Market.Logic.Storage.Repositories;
Я думал что будет репозиторий товаров. От него наследуется репозиторий продуктов, который будет имплементировать IProductRepos. В интерфейсе IProductRepo специфичные именно для продукта дополнительные методы аля AddOrUpdate. А там IProductRepo это IKeyableRepo<Product>

А в реализации просто класс будет еще и от ItemRepo наследоваться. Но интерфейсом это скрываться будет, потому что не нужно. Потому что можно отдельно IItemRepos и IProductRepo.

Ну или вообще на эти два интерфейса только одна реализация может быть например

2022-12-02 23:25 UTC, AlexBimlnk commented on Market.Logic/Storage/Repositories/IProductsRepository.cs
> +    public IEnumerable<Product> GetAllProviderProducts(Provider provider);
В целом можно просто получить список продуктов а дальше уже самим отобрать такие которые соотвествуют поставщику. Но конечно через реп это будет оптимальнее, но нужно конечно подумать будет ли это вообще использоваться, как и метод выше, или нет. Если да, то ладно, можно оставтиь

2022-12-02 23:25 UTC, AlexBimlnk commented on Market.Logic/Storage/Repositories/ProductsRepository.cs
> +    private static Provider ConvertFromStorageModel(TProvider provider) =>
почему это выше полей и конструткора??

2022-12-02 23:25 UTC, AlexBimlnk commented on Market.Logic/Storage/Repositories/ProductsRepository.cs
> +        return await _context.Products.AsNoTrackingWithIdentityResolution().ContainsAsync(new TProduct() { ItemId = key.Item1.Value , ProviderId = key.Item2.Value }, token).ConfigureAwait(false);
разбей

2022-12-02 23:25 UTC, AlexBimlnk commented on Market.Logic/Storage/Repositories/UsersRepository.cs
> +    private readonly IRepositoryContext _context;
да нахрена это выше полей и конструтора тащить, не нужно. Оставь как было

2022-12-03 08:46 UTC, wi1sp commented on Market.Logic.Tests/Storage/ProductsRepository.IntergrationTests.cs
> +        .Select(x => { x.Description = null!; x.Type = null!; return x; })
потому что селект запрос не возращает зависимые сущности

2022-12-03 08:46 UTC, wi1sp commented on Market.Logic.Tests/Storage/ProductsRepository.IntergrationTests.cs
> +            .Select(x => { x.ItemId = inputItem.Key.Value; x.Property= null!; return x; })
аналогично + в домеенной модели свойст нет ссылок на итем

2022-12-03 08:47 UTC, wi1sp commented on Market.Logic/Storage/Repositories/IProductsRepository.cs
> +    public void Update(Item item);
Ты как собрался менять описание товара?

2022-12-03 10:25 UTC, AlexBimlnk requested changes

2022-12-03 10:25 UTC, AlexBimlnk commented on Market.Logic.Tests/Storage/ProducstRepository.Tests.cs
> +/*    [Fact(DisplayName = $"The {nameof(ProductsRepository)} cannot contains product when product is null.")]
удалить

2022-12-03 10:25 UTC, AlexBimlnk commented on Market.Logic.Tests/Storage/ProducstRepository.Tests.cs
> +        Item item = null!;
зачем?

2022-12-03 10:25 UTC, AlexBimlnk commented on Market.Logic.Tests/Storage/ProductsRepository.IntergrationTests.cs
> +        dbDescription.Should().BeEquivalentTo(expectedDescription);
чем селекты такие делать лучше здесь перегрузить и исключить поля при сравнении

2022-12-03 10:57 UTC, wi1sp commented on Market.Logic.Tests/Storage/ProducstRepository.Tests.cs
> +        Item item = null!;
Там конфликт вылазит даже если к интерфейсу приводить

2022-12-04 08:11 UTC, AlexBimlnk approved these changes

2022-12-04 16:50 UTC, merged