Feature/#113 wt notify handler
AlexBimlnk/ComputerMarket pull request #149
Opened 2022-12-03 10:07 UTC by AlexBimlnk

Тесты и доделка класса будет после команд и репозитория товаров.

2022-12-04 09:20 UTC, wi1sp requested changes

2022-12-04 09:20 UTC, wi1sp commented on Market.Logic/Models/Order.cs
> +    public ID Key => throw new NotImplementedException();
Так и должно быть?

2022-12-04 09:39 UTC, AlexBimlnk commented on Market.Logic/Models/Order.cs
> +    public ID Key => throw new NotImplementedException();
Ну не я должен в рамках этого ПРа забытую функциональность добавлять.
Как будешь делать реализуешь. А пока так, чтобы не ругалось. БТВ я сейчас на команды пр сделаю и этот доделывать буду.

2022-12-05 08:16 UTC, wi1sp approved these changes

2022-12-05 15:20 UTC, merged