Feature/146 market add storage order and basket
AlexBimlnk/ComputerMarket pull request #157
Opened 2022-12-05 11:44 UTC by wi1sp

2022-12-05 15:06 UTC, AlexBimlnk commented on Market.Logic/Models/Order.cs
> +    public ID Key => throw new NotImplementedException();
?

2022-12-05 15:24 UTC, AlexBimlnk requested changes

2022-12-05 15:24 UTC, AlexBimlnk commented on Market.Logic/Storage/Repositories/IOrderRepository.cs
> +    public void AddToBasket(User user, Product product);
И типа почему у репозитория "заказов" есть логика которая связана с продуктами и только с ними. лол

2022-12-06 06:11 UTC, wi1sp commented on Market.Logic/Storage/Repositories/IOrderRepository.cs
> +    public void AddToBasket(User user, Product product);
ну ладно там теперь не продукт или ты предлагаешь это в отдельный репозиторий запихнуть

2022-12-07 13:34 UTC, AlexBimlnk requested changes
по просьбе трудящихся

2022-12-07 17:59 UTC, AlexBimlnk requested changes

2022-12-07 17:59 UTC, AlexBimlnk commented on Market.Logic/Storage/Repositories/IBasketRepository.cs
> +    /// Получение коллекции продуктво в корзине.
`продуктво`

2022-12-07 17:59 UTC, AlexBimlnk commented on Market.Logic/Storage/Models/OrderState.cs
> +public class OrderState
так зачем два ордер стейста то? просто у сторожевой id стейта будет и все. зачем это

2022-12-07 17:59 UTC, AlexBimlnk commented on Market.Logic/Models/OrderState.cs
> +public enum OrderState : int
Что по "ошибка оплаты" состоянию?

2022-12-07 19:27 UTC, AlexBimlnk approved these changes

2022-12-07 20:58 UTC, merged