Feature/#7 market create db
AlexBimlnk/ComputerMarket pull request #23
Opened 2022-09-28 06:51 UTC by wi1sp

2022-09-28 10:08 UTC, AlexBimlnk requested changes

2022-09-28 19:27 UTC, wi1sp commented on Databases/Market/DataFeed/0.sql
> +        (1,'Процессор'),
Таблицы связаны с другими по конкретным ID. Я их явно и прописал, чтобы если что-то поменяется не пришлось их везде менять.

2022-09-28 21:35 UTC, AlexBimlnk requested changes

2022-09-28 21:35 UTC, AlexBimlnk commented on Databases/Market/DataFeed/0.sql
> +           (4,1), (4,2), (4,6), -- (4,13), -- (4,8),
Не понял что это за закоменченные строки? И здесь и выше. И зачем нам заливать в реп что то закоменченное как миграцию? Есть пулим, то убираем комментарии подобные.

2022-09-28 21:35 UTC, AlexBimlnk commented on Databases/Market/Migrations/1_create_tables.sql
> +    CHECK ( Margin >= 1 )
может на всякий случай **`1.0`** забацать?

2022-09-28 21:35 UTC, AlexBimlnk commented on Databases/Market/Migrations/2_triggers.sql
> +            WHERE product.provider_id = NEW.id;
Тестил?

2022-09-28 22:55 UTC, wi1sp commented on Databases/Market/Migrations/2_triggers.sql
> +            WHERE product.provider_id = NEW.id;
Да.

2022-09-28 22:56 UTC, wi1sp commented on Databases/Market/Migrations/1_create_tables.sql
> +    CHECK ( Margin >= 1 )
Мне кажется особой разницы нет

2022-09-29 10:09 UTC, AlexBimlnk approved these changes

2022-09-29 10:27 UTC, merged